# Generated by Django 5.2.7 on 2025-10-05 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
        ('worklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='preliminary_report_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='radiologist_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='severity_grade',
            field=models.CharField(blank=True, choices=[('normal', 'Normal - No significant findings'), ('mild', 'Mild - Minor findings, routine follow-up'), ('moderate', 'Moderate - Notable findings, attention needed'), ('severe', 'Severe - Significant findings, urgent review'), ('critical', 'Critical - Life-threatening findings, immediate attention')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='severity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='urgent_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UrgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical_finding', 'Critical Finding Detected'), ('life_threatening', 'Life-Threatening Condition'), ('immediate_intervention', 'Immediate Intervention Required'), ('contrast_reaction', 'Contrast Reaction'), ('technical_failure', 'Technical Failure')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('acknowledged', 'Acknowledged'), ('in_review', 'Under Review'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('critical_findings', models.JSONField(default=list)),
                ('recommended_action', models.TextField()),
                ('severity_score', models.FloatField()),
                ('estimated_time_sensitivity', models.IntegerField(help_text='Minutes until intervention needed')),
                ('notification_methods_used', models.JSONField(default=list)),
                ('first_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('notification_attempts', models.IntegerField(default=0)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('ai_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_alerts', to='ai_analysis.aianalysis')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklist.study')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
